/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestingTest;

import org.junit.Test;
import static org.junit.Assert.*;

public class MyTest {@Test
    public void multiplicationOfZeroIntegersShouldReturnZero() {
        MyClass tester = new MyClass(); // MyClass is tested

        // assert statements
        assertEquals("10 x 0 must be 0", 0, tester.multiply(10, 0));
        assertEquals("0 x 10 must be 0",0, tester.multiply(0, 10));
        assertEquals("0 x 0 must be 0",0, tester.multiply(0, 0));  
        //assertEquals()    
        //assertEquals("0 x 0 = 0 ",0,tester.multiply(0, 0));
    }
}
