/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oracle.tutorial.testing;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testApp() {
        Bicycle bicycleClass = new Bicycle(0, 0, 0);
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        int temp = 0;
        for(int a = 0;bicycleClass.getSpeed()<=5;a++)
        {
            temp += a;
            bicycleClass.speedUp(a);
            assertEquals("Current Speed must be "+temp, bicycleClass.getSpeed(),temp);
        }

    }
}
