/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MariaDBGradleConnect;
import java.sql.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main( String[] args ) throws SQLException {
        //create connection for a server installed in localhost, with a user "root" with no password
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/DB?user=admin&password=admin")) {
            // create a Statement
            try (Statement stmt = conn.createStatement()) {
                //execute query
                try (ResultSet rs = stmt.executeQuery("SELECT 'Hello World!'")) {
                    //position result to first
                    rs.first();
                    System.out.println(rs.getString(1)); //result is "Hello World!"
                }
            }
        }
    }
}
